server:
  port: 9095
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
          web:
            exposure:
              include: gateway
  health:
    circuitbreakers:
        enabled: true

token:
  issuer:
      url: http://localhost:8089
      x509: /home/elbatouri/IdeaProjects/jwt-spring-boot/service-provider/keystore/token-issuer-x509.txt

service:
  provider:
    url: http://localhost:9090/
    x509: /home/elbatouri/IdeaProjects/jwt-spring-boot/service-provider/keystore/service-provider-x509.txt
    pkcs12: /home/elbatouri/IdeaProjects/jwt-spring-boot/service-provider/keystore/service-provider-pkcs.p12